### ISSUE TITLE
Issues with Fortran and MPI_IN_PLACE

### ISSUE THREAD

**Issue by mkre** [eschnett/MPIwrapper#20]
I am having some problems in understanding the mechanisms behind Fortran sentinel values like `MPI_IN_PLACE`.

We are seeing a Fortran code crashing when making use of `MPI_IN_PLACE`. It turns out when calling into the MPI library (Open MPI), `MPI_IN_PLACE` has the value `0x0`. However, in fact it is defined as `0x1` in Open MPI, so this will obviously crash.

I added some debug statements to MPIwrapper and it seems like the value of `MPI_IN_PLACE` [here](https://github.com/eschnett/MPIwrapper/blob/v2.10.4/src/mpiwrapper.f#L17) (printed via  `print *, MPI_IN_PLACE`) is indeed `0x0`, even though it should come from Open MPI's `mpif.h` which I assume should correctly define it as `0x1`. When printing the value of `MPI_IN_PLACE` in `mpiwrapper.cxx` instead, it has the correct value of `0x1`.

I am not sure if I am looking in the correct spot. It might be an issue in MPItrampoline rather than MPIwrapper, or even somewhere else in our tool chain. Any help or suggestions for further troubleshooting would be highly appreciated.

Thanks,
Moritz

**Comment by eschnett** [comment]
Values such as `MPI_IN_PLACE` are confusing because Fortran passes arguments by reference. `MPI_IN_PLACE` is not a particular value, but it is rather has an arbitrary (probably even undefined) value. Rather this is a "global" variable that lives at a particular place in memory, and the C code in OpenMPI checks the address of that value to see whether you passed `MPI_IN_PLACE`. I think this value lives (pretends to live) at the memory address `0x1`.

Printing this arbitrary value from Fortran isn't useful. You might be able to print `loc(MPI_IN_PLACE)` from Fortran, which should report the same values independently of whether you build against OpenMPI, or build against MPItrampoline and then run with OpenMPI.

MPItrampoline treats `MPI_IN_PLACE` as a Cray pointer, a Fortran extension. I don't know whether the `loc` output above works with pointers. However, in MPItrampoline you can print the value of `MPI_IN_PLACE_PTR` which should be the same as `loc(MPI_IN_PLACE)` for OpenMPI, which should presumably be `0x1`.

**Comment by mkre** [comment]
> Values such as `MPI_IN_PLACE` are confusing because Fortran

This :). I am still trying to wrap my head around it.

In MPIwrapper's `mpifrapper.f` I can print the following after including Open MPI's `mpif.h`:
```
mpiwr loc(MPI_IN_PLACE)      140534033384800
mpiwr MPI_IN_PLACE           0 
```

The first one seems to be an "arbitrary (probably even undefined) value", but I would have assumed that the `loc()` is well-defined (`0x1`) and the second line should print an arbitrary value. What makes it even more confusing is that the final Fortran code (MUMPS) relying on MPIwrapper/MPItrampoline will print the following after including MPItrampoline's `mpif.h`:
```
mumps loc(MPI_IN_PLACE)                    0
mumps MPI_IN_PLACE           0
```

So it seems like for some reason the correct `loc()` (which according to your message should be constant across the entire lifetime?) got lost somewhere. I will probably need to take some more time to understand everything here.

**Comment by eschnett** [comment]
The `mpiwr` output looks correct. The address isn't quite arbitrary, it's where the compiler happens to place a global variable in memory. OpenMPI uses that variable's address to indicate that the caller specified `MPI_IN_PLACE`.

The `mumps` output then does not look correct. Somehow this address got lost.

Can you also output `MPI_IN_PLACE_PTR`? This is not an official MPI constant, but a helper variable that MPIwrapper and MPItrampoline use to communicate this address.

**Comment by mkre** [comment]
> Can you also output `MPI_IN_PLACE_PTR`? This is not an official MPI constant, but a helper variable that MPIwrapper and MPItrampoline use to communicate this address.

This is the combined output for a two-process run (hence everything appears twice).
```
 mpiwr loc(MPI_IN_PLACE)      139626642896224
 mpiwr MPI_IN_PLACE           0
 mpiwr loc(MPI_IN_PLACE)      139777338373472
 mpiwr MPI_IN_PLACE           0
 mumps loc(MPI_IN_PLACE)                    0
 mumps MPI_IN_PLACE           0
 mumps loc(MPI_IN_PLACE_PTR)      139774358695680
 mumps MPI_IN_PLACE_PTR                    0
 mumps loc(MPI_IN_PLACE)                    0
 mumps MPI_IN_PLACE           0
 mumps loc(MPI_IN_PLACE_PTR)      139623916199680
 mumps MPI_IN_PLACE_PTR                    0
```

Seems like `loc(MPI_IN_PLACE_PTR)` is not zero (which is correct), but still different from `loc(MP_IN_PLACE)`. I cannot print this value from the MPIwrapper because it is not defined there.

**Comment by eschnett** [comment]
The value of `MPI_IN_PLACE_PTR` in MPItrampoline should be the same as `loc(MPI_IN_PLACE)` in MPIwrapper. This is the value that OpenMPI ultimately uses to detect whether you are using `MPI_IN_PLACE`. Something is not working right.

What system are you using? Which versions of which libraries are you using?

**Comment by mkre** [comment]
@eschnett, I found the root cause. As expected, nothing was wrong with MPItrampoline/MPIwrapper, but the issue was at a different place in our software stack. What helped me in the end was the construction of a minimal Fortran code where I print the aforementioned constants/locations (which was giving the expected results), and then finding the difference in terms of code/compilation/linking compared to MUMPS (which was giving the unexpected results).

MUMPS is shipping its own pseudo MPI library "libseq" to be used for strictly _serial_ builds (not supporting MPI). In order to make this usable with MPItrampoline and have the right symbols picked up at run time, we are building MUMPS with `-Wl,-Bsymbolic`. However, that flag is causing the observed issues with `MPI_IN_PLACE` and Fortran for _parallel_ MUMPS builds. The fix is to only add this flag to serial MUMPS builds, but avoid adding it for parallel MUMPS builds.

Thanks a lot for your help here. Without your pointers (pun intended), I probably wouldn't have found the issue so quickly.

**Comment by eschnett** [comment]
@mkre Thanks for the heads-up!
