### ISSUE TITLE
HAVE_MPIX_QUERY_CUDA_SUPPORT incorrectly reporting a failure?

### ISSUE THREAD

**Issue by Sbozzolo** [eschnett/MPIwrapper#23]
I am using [this code](https://gist.github.com/K-Wu/6c353273aafe9a4eaaa344a8b74475b6) to check if my installation of OpenMPI is CUDA aware. On the system I am working on, the code returns:
```
Run time check:
This MPI library has CUDA-aware support.
Compile time check:
This MPI library has CUDA-aware support.
```
This is what I am expecting (I used this library for CUDA-MPI runs).

However, when I configure MPIwrapper, I see that:
```
-- Performing Test HAVE_MPI_EXT
-- Performing Test HAVE_MPI_EXT - Success
-- Performing Test HAVE_MPIX_QUERY_CUDA_SUPPORT
-- Performing Test HAVE_MPIX_QUERY_CUDA_SUPPORT - Failed
-- Performing Test HAVE_MPIX_QUERY_HIP_SUPPORT
-- Performing Test HAVE_MPIX_QUERY_HIP_SUPPORT - Failed
-- Performing Test HAVE_MPIX_QUERY_ZE_SUPPORT
-- Performing Test HAVE_MPIX_QUERY_ZE_SUPPORT - Failed
```

I am using the latest release of MPIwrapper and OpenMPI 4.1.5

**Comment by eschnett** [comment]
Which versions of MPIwrapper and MPItrampoline are you using?

**Comment by Sbozzolo** [comment]
I am using the latest release of MPIwrapper (2.10.5) as downloaded from GitHub, and MPITrampoline 5.3.2 through the jll.

**Comment by eschnett** [comment]
Can you post your `CMakeOutput.log` and `CMakeError.log`?

**Comment by eschnett** [comment]
Did you remove (`rm -rf`) your build files after updating to MPIwrapper 2.10.5? There was an error before this version.

**Comment by eschnett** [comment]
Found the bug. Will release a new version soon.

**Comment by Sbozzolo** [comment]
Thank you!
