### ISSUE TITLE
Building MPIwrapper with OpenMPI fails on Linux + x86

### ISSUE THREAD

**Issue by kvoronin** [eschnett/MPIwrapper#28]
Hi!

When trying to build MPIwrapper with OpenMPI (tried 3.1.5 and 4.1.5), gcc (tried 7.5.0, 9.3.0 and 13.3.0) with a command like
`
cmake -S . -B ${BUILD_DIR} \
    -DMPIEXEC_EXECUTABLE=mpiexec -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_C_COMPILER=/home/utils/gcc-9.3.0/bin/gcc \
    -DCMAKE_CXX_COMPILER=/home/utils/gcc-9.3.0/bin/g++ \
    -DCMAKE_Fortran_COMPILER=/home/utils/gcc-9.3.0/bin/gfortran \
    -DCMAKE_INSTALL_PREFIX=./${BUILD_DIR}/mpiwrapper
cmake --build build
cmake --install build
`
I am getting errors:
`
[ 20%] Generating src/mpiabi_defn_constants_c.h, src/mpiabi_defn_functions_c.h, src/mpiabi_defn_constants_fortran.h, src/mpiabi_defn_functions_fortran.h
[ 40%] Generating src/mpiabi_decl_constants_c.h, src/mpiabi_decl_functions_c.h, src/mpiabi_decl_constants_fortran.h, src/mpiabi_decl_functions_fortran.h
Scanning dependencies of target mpiwrapper
[ 60%] Building CXX object CMakeFiles/mpiwrapper.dir/src/mpiwrapper.cxx.o
In file included from .../MPIwrapper/src/mpiwrapper.cxx:133:
.../MPIwrapper/build/src/mpiabi_defn_constants_c.h:169:59: error: ‘MPI_COMPLEX32’ was not declared in this scope; did you mean ‘MPI_COMPLEX16’?
  169 | MPIABI_Datatype const MPIABI_COMPLEX32 = (MPIABI_Datatype)MPI_COMPLEX32;
      |                                                           ^~~~~~~~~~~~~
      |                                                           MPI_COMPLEX16
/home/scratch.kvoronin_sw/libraries/MPIwrapper/build/src/mpiabi_defn_constants_c.h:208:56: error: ‘MPI_REAL16’ was not declared in this scope; did you mean ‘MPI_REAL4’?
  208 | MPIABI_Datatype const MPIABI_REAL16 = (MPIABI_Datatype)MPI_REAL16;
      |                                                        ^~~~~~~~~~
      |                                                        MPI_REAL4
CMakeFiles/mpiwrapper.dir/build.make:116: recipe for target 'CMakeFiles/mpiwrapper.dir/src/mpiwrapper.cxx.o' failed
`

I also see some suspicious places in the OpenMPI doc which seem to be related: 
https://www.open-mpi.org/faq/?category=building#mpi_real16

Could you help me understand how to solve this issue? My ultimate goal is to use MPITrampoline as a communication layer with OpenMPI backend (and taking in device buffers (allocated via cudaMalloc), hopefully that's possible as OpenMPI supports it?)

Thanks,
Kirill

**Comment by kvoronin** [comment]
Upd: problem solved, there was a misconfiguration with multiple out-dated openmpi versions flying around.

**Comment by eschnett** [comment]
Glad to hear it's solved!
